### ISSUE TITLE
Get Issue starting the viewing script

### ISSUE THREAD

**Issue by jeezrick** [Florian-Barthel/splatviz#12]
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (1, b'Texture\x00'),
	result = -1
)

Is this because my opengl version?

**Comment by Florian-Barthel** [comment]
Hi,
can you provide some more information to reproduce this error? Like, which opengl version do you use?
