### ISSUE TITLE
Is it possible to use it with a headless machine?

### ISSUE THREAD

**Issue by weiyunpei** [Florian-Barthel/splatviz#19]
hello, really amazing work.
But I wonder if I could use the viewer on a headless machine such as a workstation.
Thanks for your job again.

**Comment by Florian-Barthel** [comment]
Thank for your kind words!

Yes, that's one of the plans for the future. This could be implemented similarly as in the SIBR viewer from the official 3DGS repository. Where the client sends camera parameters and the server responds with renderings.

Then, you would also be able attach the viewer to a live training process and the viewer would be compatible with macOS.

**Comment by weiyunpei** [comment]
Thanks for your kindly reply!

**Comment by Florian-Barthel** [comment]
This is now implemented in the latest version of splativz
