### ISSUE TITLE
How to use for viewing Dynamic Scenes?

### ISSUE THREAD

**Issue by IQRAASGHAR1999** [Florian-Barthel/splatviz#26]
Hey, I have tried using this for dynamic scenes but it shows only the static scene in the viewer. Can this tool help in viewing dynamic scenes?
https://github.com/hustvl/4DGaussians

**Comment by Florian-Barthel** [comment]
Hi,
it would be cool if the viewer also supports 4DGS. Currently, however, only 3D scenes can be rendered. 

In what kind of format do you store 4DGS files. A list of ply files?

**Comment by Florian-Barthel** [comment]
Closed for now due to inactivity. One day splatviz will support 4DGS, however, currently its not a high priority.

**Comment by xiao10ma** [comment]
Thank you very much for sharing this repo! If you happen to release a version related to 4DGS in the future, I’d be very interested and would love to learn more. Thanks again for your work!
