### ISSUE TITLE
Look cool not real a issue

### ISSUE THREAD

**Issue by antoinebou12** [Florian-Barthel/splatviz#27]
https://research.nvidia.com/labs/toronto-ai/simplicits/
https://www.youtube.com/watch?v=3Zameqg66aA&embeds_referring_euri=https%3A%2F%2Fresearch.nvidia.com%2F&source_ve_path=Mjg2NjY

**Comment by Florian-Barthel** [comment]
Look into https://github.com/MrNeRF/awesome-3D-gaussian-splatting for other cool 3DGS research :)
