### ISSUE TITLE
Adding a slider with a name that's already taken crashes

### ISSUE THREAD

**Issue by w-m** [Florian-Barthel/splatviz#31]
Add a slider "x", add a slider "x" again, crash.

Adding one with the same name should probably just overwrite the previous one?

**Comment by Florian-Barthel** [comment]
Fixed in [acf5b23](https://github.com/Florian-Barthel/splatviz/commit/acf5b23cea4b3467e6e43c6818d669d7d1ad7e03). Sliders have an ID now :)
