### ISSUE TITLE
Edit Widget persistence

### ISSUE THREAD

**Issue by w-m** [Florian-Barthel/splatviz#32]
Would be great if the sliders and text of the Edit Widget is persistent through exits/crashes and relaunches of splatviz. It's easy to blow up the CUDA renderer by dragging a slider somewhere it wasn't supposed to go. Or hit Escape by accident. And you have to rebuild everything after (if you hadn't set it as preset already).

Loading it automatically may not be super helpful if you wrote some code that barely crashes, could throw into a crash loop. Maybe have the last working version ("working" defined as fully passing through the renderer) as an automatic "Previous Session" preset?

**Comment by Florian-Barthel** [comment]
With [8a6065c](https://github.com/Florian-Barthel/splatviz/commit/8a6065cc57fedb4fcb929249e26a5838124f47ec), there is now a history of previous edit sessions. To ensure that there is no crash loop, I have added a "safe load" option that loads the last session in a commented out string like this:

```python
''' # REMOVE THIS LINE
mask = torch.linalg.norm(gaussian._xyz, dim=-1) < slider.x

gaussian._xyz = gaussian._xyz[mask]
gaussian._rotation = gaussian._rotation[mask]
gaussian._scaling = gaussian._scaling[mask]
gaussian._opacity = gaussian._opacity[mask]
gaussian._features_dc = gaussian._features_dc[mask]
gaussian._features_rest = gaussian._features_rest[mask]
self.bg_color[:] = 1

''' # REMOVE THIS LINE
```
