### ISSUE TITLE
GUI Window Not Showing

### ISSUE THREAD

**Issue by shuohantao** [Florian-Barthel/splatviz#37]
I've installed the repo as the readme suggests on a Windows ocmputer. When I run python run_main.py in anaconda terminal with the provided sample scene, the gui window doesn't show and the program terminates after a few seconds. The viz.should_close() isn't triggered, and the draw_frame is only called once within the loop, no errors or exceptions are detected either. viz.close() isn't triggered as well, and the draw_frame successfully executes to the last line of self.end_frame().

**Comment by Florian-Barthel** [comment]
How did you fix it?
